---
# change  token , apiServerEndpoint, caCertHashes and name(hostname) for each node
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "ay0ypz.05oy6q3unoq3ayn5"
    apiServerEndpoint: "10.22.1.206:6443"
    caCertHashes:
      - "sha256:4e7cfd4a43653d1fd4127cba67005e13f3491776a4dd883e702b03c0f79c218d"
nodeRegistration:
  name: ip-10-22-1-66.us-west-1.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws
