---
# change  token , apiServerEndpoint, caCertHashes and name(hostname) for each node
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "fdloz8.lfcscmdalf5mhfdi"
    apiServerEndpoint: "10.22.1.243:6443"
    caCertHashes:
      - "sha256:2faa104b20308e089a379e80ea505681eaca70444c28529babc9a7e2894b3c60"
nodeRegistration:
  name: ip-10-22-1-34.us-west-1.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws
